// ═══════════════════════════════════════════════════════════
//  mapping_data.js — Table de correspondance motifs Pronote
//  Généré automatiquement depuis le TDB Vie Scolaire
//  Date : 18/03/2026
//  Pour appliquer : remplacer intégralement ce fichier,
//  puis recharger l'application dans le navigateur.
// ═══════════════════════════════════════════════════════════

const MAPPING_DEFAULT_DATA = { mapping: {
  // ── Perturbation du cours / bavardage
  "Agitation"                                                                               : "Perturbation du cours / bavardage",
  "Attitude perturbatrice persistante"                                                      : "Perturbation du cours / bavardage",
  "Bavardage"                                                                               : "Perturbation du cours / bavardage",
  "Bavardages"                                                                              : "Perturbation du cours / bavardage",
  "Bavardages incessants"                                                                   : "Perturbation du cours / bavardage",
  "Chahut"                                                                                  : "Perturbation du cours / bavardage",
  "Comportement perturbateur"                                                               : "Perturbation du cours / bavardage",
  "Dérange le bon déroulement du cours"                                                     : "Perturbation du cours / bavardage",
  "Dissipation"                                                                             : "Perturbation du cours / bavardage",
  "Manque de sérieux dans le travail"                                                       : "Perturbation du cours / bavardage",
  "Oubli répété du matériel"                                                                : "Perturbation du cours / bavardage",
  "Perturbation du cours"                                                                   : "Perturbation du cours / bavardage",
  "Refus d'obéir"                                                                           : "Perturbation du cours / bavardage",
  "Refus de travailler"                                                                     : "Perturbation du cours / bavardage",
  "Travail non fait"                                                                        : "Perturbation du cours / bavardage",

  // ── Insolence / irrespect / refus
  "Accusations mensongères à l'encontre d'un personnel"                                     : "Insolence / irrespect / refus",
  "Attitude générale inappropriée au cadre scolaire"                                        : "Insolence / irrespect / refus",
  "Contestation de l'autorité"                                                              : "Insolence / irrespect / refus",
  "Crachat"                                                                                 : "Insolence / irrespect / refus",
  "Dort en classe"                                                                          : "Insolence / irrespect / refus",
  "Geste déplacé"                                                                           : "Insolence / irrespect / refus",
  "Incivisme"                                                                               : "Insolence / irrespect / refus",
  "Insolence"                                                                               : "Insolence / irrespect / refus",
  "Irrespect"                                                                               : "Insolence / irrespect / refus",
  "Manque de respect envers un personnel"                                                   : "Insolence / irrespect / refus",
  "Mensonges"                                                                               : "Insolence / irrespect / refus",
  "Propos irrespectueux"                                                                    : "Insolence / irrespect / refus",
  "Quitte un cours d'EPS sur le trajet"                                                     : "Insolence / irrespect / refus",
  "Refus d'obéissance"                                                                      : "Insolence / irrespect / refus",
  "Refus de travail"                                                                        : "Insolence / irrespect / refus",
  "Spectateur d'une bagarre"                                                                : "Insolence / irrespect / refus",
  "Triche"                                                                                  : "Insolence / irrespect / refus",

  // ── Violence verbale / menaces (entre élèves)
  "Écart de langage"                                                                        : "Violence verbale / menaces (entre élèves)",
  "Insulte"                                                                                 : "Violence verbale / menaces (entre élèves)",
  "Insultes entre élèves"                                                                   : "Violence verbale / menaces (entre élèves)",
  "Langage inapproprié"                                                                     : "Violence verbale / menaces (entre élèves)",
  "Menaces"                                                                                 : "Violence verbale / menaces (entre élèves)",
  "Menaces entre élèves"                                                                    : "Violence verbale / menaces (entre élèves)",
  "Propos graves et inapproriés à caractère provocateur"                                    : "Violence verbale / menaces (entre élèves)",
  "Propos insultants envers un élève"                                                       : "Violence verbale / menaces (entre élèves)",
  "Propos racistes"                                                                         : "Violence verbale / menaces (entre élèves)",
  "Provocations verbales"                                                                   : "Violence verbale / menaces (entre élèves)",
  "Violence verbale"                                                                        : "Violence verbale / menaces (entre élèves)",
  "Violence verbale à caractère sexuel"                                                     : "Violence verbale / menaces (entre élèves)",
  "Violence verbale entre élèves"                                                           : "Violence verbale / menaces (entre élèves)",

  // ── Violence physique (entre élèves)
  "Agression"                                                                               : "Violence physique (entre élèves)",
  "Bagarre"                                                                                 : "Violence physique (entre élèves)",
  "Bousculade volontaire"                                                                   : "Violence physique (entre élèves)",
  "Coups et blessures entre élèves"                                                         : "Violence physique (entre élèves)",
  "Geste violent envers un camarade"                                                        : "Violence physique (entre élèves)",
  "Happy slapping"                                                                          : "Violence physique (entre élèves)",
  "incite à la bagarre"                                                                     : "Violence physique (entre élèves)",
  "Jeu dangereux et violent"                                                                : "Violence physique (entre élèves)",
  "Jeux puérils"                                                                            : "Violence physique (entre élèves)",
  "Violence physique"                                                                       : "Violence physique (entre élèves)",
  "Violence physique entre élèves"                                                          : "Violence physique (entre élèves)",
  "Voies de fait"                                                                           : "Violence physique (entre élèves)",

  // ── Violence envers un adulte
  "Agression d'un personnel"                                                                : "Violence envers un adulte",
  "Croche pied à un professeur"                                                             : "Violence envers un adulte",
  "Insultes envers un adulte"                                                               : "Violence envers un adulte",
  "Menaces envers un personnel"                                                             : "Violence envers un adulte",
  "Violence envers un adulte"                                                               : "Violence envers un adulte",
  "Violences physiques envers un adulte"                                                    : "Violence envers un adulte",
  "Violences verbales envers un adulte"                                                     : "Violence envers un adulte",

  // ── Harcèlement / pressions
  "Cyber-harcèlement"                                                                       : "Harcèlement / pressions",
  "Exerce des pressions sur des camarades"                                                  : "Harcèlement / pressions",
  "Harcèlement"                                                                             : "Harcèlement / pressions",
  "Harcèlement entre élèves"                                                                : "Harcèlement / pressions",
  "Intimidation"                                                                            : "Harcèlement / pressions",
  "Pressions sur un élève"                                                                  : "Harcèlement / pressions",
  "Racket"                                                                                  : "Harcèlement / pressions",

  // ── Numérique / réseaux sociaux / téléphone
  "Cyberbullying"                                                                           : "Numérique / réseaux sociaux / téléphone",
  "Diffusion d'une image privée sans le consentement de la personne sur les réseaux sociaux": "Numérique / réseaux sociaux / téléphone",
  "Participation à un groupe sur les reseaux"                                               : "Numérique / réseaux sociaux / téléphone",
  "Propos graves et menaçant sur les réseaux sociaux"                                       : "Numérique / réseaux sociaux / téléphone",
  "Publication non autorisée"                                                               : "Numérique / réseaux sociaux / téléphone",
  "Réseaux sociaux"                                                                         : "Numérique / réseaux sociaux / téléphone",
  "Téléphone portable"                                                                      : "Numérique / réseaux sociaux / téléphone",
  "Usage du téléphone"                                                                      : "Numérique / réseaux sociaux / téléphone",
  "Utilisation d'un téléphone portable"                                                     : "Numérique / réseaux sociaux / téléphone",
  "Utilisation du téléphone portable"                                                       : "Numérique / réseaux sociaux / téléphone",
  "Utilisation non autorisée d'un appareil numérique"                                       : "Numérique / réseaux sociaux / téléphone",

  // ── Dégradations / vols / sécurité
  "Dégradation de matériel"                                                                 : "Dégradations / vols / sécurité",
  "Dégradation des locaux"                                                                  : "Dégradations / vols / sécurité",
  "Détérioration de matériel"                                                               : "Dégradations / vols / sécurité",
  "Graffitis"                                                                               : "Dégradations / vols / sécurité",
  "Incendie volontaire"                                                                     : "Dégradations / vols / sécurité",
  "Introduction d'une arme au sein du collège"                                              : "Dégradations / vols / sécurité",
  "Intrusion"                                                                               : "Dégradations / vols / sécurité",
  "Intrusion de personnes étrangères à l'établissement"                                     : "Dégradations / vols / sécurité",
  "Port d'arme ou d'objet dangereux"                                                        : "Dégradations / vols / sécurité",
  "Possession d'une arme au sein de l'établissement"                                        : "Dégradations / vols / sécurité",
  "se soustrait à la surveillance du professeur"                                            : "Dégradations / vols / sécurité",
  "Suspicion d'introduction d'arme au collège"                                              : "Dégradations / vols / sécurité",
  "Tentative de vol"                                                                        : "Dégradations / vols / sécurité",
  "Vol"                                                                                     : "Dégradations / vols / sécurité",
  "Vols"                                                                                    : "Dégradations / vols / sécurité",

  // ── Atteinte à la laïcité
  "Atteinte à la laïcité"                                                                   : "Atteinte à la laïcité",
  "Contestation du contenu d'enseignement"                                                  : "Atteinte à la laïcité",
  "Discrimination"                                                                          : "Atteinte à la laïcité",
  "Port de signes religieux ostentatoires"                                                  : "Atteinte à la laïcité",
  "Prosélytisme"                                                                            : "Atteinte à la laïcité",

  // ── Non-respect du RI / autre
  "Absence injustifiée"                                                                     : "Non-respect du RI / autre",
  "Autre"                                                                                   : "Non-respect du RI / autre",
  "Consommation de produits interdits"                                                      : "Non-respect du RI / autre",
  "défaut de matériel"                                                                      : "Non-respect du RI / autre",
  "Dégradation"                                                                             : "Non-respect du RI / autre",
  "Fausse identité"                                                                         : "Non-respect du RI / autre",
  "Fume une puff au collège"                                                                : "Non-respect du RI / autre",
  "Introduction de nourriture non autorisée"                                                : "Non-respect du RI / autre",
  "Jets de projectiles"                                                                     : "Non-respect du RI / autre",
  "Non renseigné"                                                                           : "Non-respect du RI / autre",
  "Non respect du RI"                                                                       : "Non-respect du RI / autre",
  "Non-respect du règlement intérieur"                                                      : "Non-respect du RI / autre",
  "Oubli de matériel"                                                                       : "Non-respect du RI / autre",
  "Rattrapage de contrôle"                                                                  : "Non-respect du RI / autre",
  "Retard répété"                                                                           : "Non-respect du RI / autre",
  "Retards"                                                                                 : "Non-respect du RI / autre",
  "Retenue non faite donc doublée"                                                          : "Non-respect du RI / autre",
  "Sèche les cours"                                                                         : "Non-respect du RI / autre",
  "Tenue non conforme"                                                                      : "Non-respect du RI / autre",
}};
